discord-akairo/discord-akairo

- src/struct/CommandHandler.js
If `command.userPermissions` or `command.clientPermissions` is a _function_, it only works if **false** is returned. Looking at the source code, the problem is that if the first "if" statement fails (even if `command.userPermissions` is a function), the next statement assumes that `command.userPermissions` is a valid permission value, which it is not - it's an object of the function.
If the example userPermissions function displayed in the [gitbooks tutorials page](https://1computer1.gitbooks.io/akairo-tutorials/content/tutorials/commands/permissions.html)  returns **true**, this error gets thrown:
```
RangeError: Invalid permission string or number.
at Function.resolve (D:\WORK\workspace-new\Projects\discord\node_modules\discord.js\src\util\Permissions.js:168:65)
at Permissions.has …
```
> Fixed unexpected dynamic permission behavior

- src/struct/AkairoHandler.js
Currently, when calling `readdirRecursive`, it returns an array including the full filepath of each file. Then, AkairoHandler attempts to compare the file name included (ex. `Eval.js`) to the full file path (ex. `C:\\Users\\Owner\\Desktop\\Development\\Slice\\src\\Commands\\Owner\\Eval.js`). This means it will never find the file called `Eval.js` unless we were to include the full path *or compare it to the basename of the file*, in which this PR does.
Example eval to test.
```js
sa$eval const path = require('path');
const files = this.handler.constructor.readdirRecursive(this.handler.directory);
files.find(f => {
return path.basename(f) == 'Eval.js';
});
```
> Fix AkairoHandler#add

- src/struct/CommandUtil.js
I had a problem with my embeds not being edited.
hasFiles was returning an array and since `![]` is false, the embeds couldn't be edited.
So now hasFiles is either true or false. 😊
> Fixed embeds not being edited

- src/struct/AkairoHandler.js
Passing the current context will prevent `this` from referencing something else than the AkairoHandler class and throw an error when trying to access the `classToHandle` property.
> Fixed AkairoHandler findExport

- src/index.d.ts
- src/struct/commands/Command.js
- src/struct/commands/CommandHandler.js
- src/util/Constants.js
- test/commands/lock.js
Allows the restriction of concurrent command usage. Useful for commands that take a while, use awaitMessages, etc.
> Feat: Command Locks

- src/index.d.ts
This was named afterContent (probably a left over)
https://github.com/1Computer1/discord-akairo/blob/d404e6f7e0a98c71708801d5ce5d163b224a88e2/src/struct/commands/CommandUtil.js#L173-L181
https://github.com/1Computer1/discord-akairo/blob/e901a1e25b871e61782877508c5de9e56ea4cd60/src/struct/commands/CommandHandler.js#L809-L816
> Fix typings for ParsedComponentData

- src/index.d.ts
ClientUtil#collection causes TS error when invoked without passing an iterable, which it should not:
> Typings: ClientUtil#collection parameter should be optional

- src/index.d.ts
- **emitError** - JSDoc has `command` parameter optional but TS definition requires it, which doesn't seem to be the case for `CommandHandler#handle`.
- **parseCommand`With`OverwrittenPrefixes** => **parseCommandOverwrittenPrefixes**
- **useInhibitorHandler** and **useListenerHandler** - `: void` => `: CommandHandler`
- **error** - Likewise with `emitError` method.
> Typings: Reflect CommandHandler changes

- src/index.d.ts
`prompt: true` in args caused TypeScript to error because it needed for an object, added boolean to typings to it can be used. It caused impossibility to use the `defaultPrompt` of `CommandHandler`
> Updated typings

- src/index.d.ts
Reflects the [docs](https://1computer1.github.io/discord-akairo/master/global.html#AkairoHandlerOptions)
> typings: classToHandle takes Function instead of string

- src/struct/ClientUtil.js
The rest of the check functions default caseSensitive and wholeWord to false, except checkGuild, this aims to fix that
> bring checkGuild inline with the rest of the checks

- docs/arguments/custom.md
- docs/arguments/functions.md
TypeCasters docs were outdated, and were only applied to the stable version of TypeCasters.
- Updated docs for `docs/arguments/custom.md`
- Updated docs for `docs/arguments/functions.md`
While there might be other outdated documentation, I wanted to fix this first cause it confused a lot of people who install master for the first time (and only read the guide and not the actual reference).
One more thing, I was going to make an issue about this, but it really doesn't belong to this repo.
The links that are used to link between pages, for example `docs/arguments/functions.md#119`, they do work on GitHub, but they don't work on the GitHub pages website. So... you might do something in discord.js's Vue app since it's a virtual DOM/single- page app (don't know what to call it) and it …
> Updated docs(TypeCasters) to master version

- src/index.d.ts
This is important so you can overwrite for example the `prefix` key in `CommandHandlerOptions` to not always have typecast it with `(this.handler.prefix as PrefixSupplier)(msg);` all over the place.
```ts
declare module 'discord-akairo' {
interface CommandHandlerOptions {
prefix: PrefixSupplier
}
}
```
> refactor(typings): types to interfaces

- src/struct/commands/arguments/TypeResolver.js
Update's the Akairo TypeResolver to support the pending change from DataStores to Managers in discord.js v12.
I couldn't see anywhere else that actually referenced the DataStores, or any mention of them in the typings, but good chance I missed something anyway.
Ref: https://github.com/discordjs/discord.js/pull/3696
Because I didn't want to change the dependency in `package.json` for this PR, a version of Akairo which uses the discord.js fork as it's dependency can be tested by installing `Monbrey/discord.js#remove-datastores-test`
> [DO NOT MERGE]: fix(TypeResolver): Update TypeResolver for future DataStore removal

- src/struct/commands/CommandUtil.js
Steps to reproduce:
1) let bot respond to a command, having editable + command util enabled
2) delete bot response
3) edit the message with another response
expected: bot sends a new message
actual: DiscordAPI error because the deleted message can not be edited
This PR attempts to solve this by checking for a deletion before letting the CommandUtil edit the response
The message being sent as a new message instead seems to be the intended and most expected result in this case (as that's imo the entire point behind cmdutil, to handle edits dynamically, and instead send if not possible to edit), should you disagree let me know.
> fix(CommandUtil): check for the response to be deleted before trying to edit

- docs/basics/listeners.md
- docs/listeners/emitters.md
Suggest to add additional documentation to the guide, to call `setEmitters` before `load` or `loadAll`. Otherwise it will trigger `AkairoError [INVALID_TYPE]: Value of 'emitter' was not an EventEmitter`. API users should not usually have to concern themselves with what is going on behind the scenes, therefore documentation should state if certain steps have to be carried out in a specific order.
> docs: call setEmitters before load

- src/struct/commands/CommandHandler.js
- test/commands/condition.js
- test/commands/condition.promise.js
Currently if a command's `condition` returns a promise, it would always run the command as it does not resolve the promise.
This PR fixes that by checking for the promise and resolving it if applicable.
*This does not break `handleConditionalCommands`, it already returns a Promise.*
Additionally, I've added tests or both normal and promise conditional commands.
> feat: support promises in command conditions

- src/struct/commands/arguments/ArgumentRunner.js
When executing `Argument.runSeparate`, provided arguments are pushed into an array, but if a user provides an incorrect argument type and cancels the prompt, a cancel `Flag` is generated but it's pushed into the array. Since the `flag` is in an `Array`, `Argument.isShortCircuit` returns false and the command executes, even though the user cancelled.
If the `args` array for a command is:
```javascript
// command aliases: numbers
[
{
id: 'amount',
match: 'separate',
type: 'number',
prompt: { start: 'please provide a valid number.', retry: 'please provide a valid number to use.' },
}
]
```
and you execute the command with:
```
!numbers not_a_number1 not_a_number2
```
As the arguments aren't numbers, the user will be prompted to provide a valid argument for each invalid argument. So they're …
> fix: return a cancel flag if a user cancels a prompt

- docs/arguments/prompts.md
In the prompts documentation, the example of "modifyStart" and "modifyRetry" was incorrect, as the first parameter it used was the text, where it is, in reality, the message.
> fix(docs): Fix function parameters in modifyPrompt

- src/index.d.ts
- src/struct/commands/Command.js
- src/struct/commands/CommandUtil.js
- src/struct/commands/arguments/Argument.js
This replaces all references to `StringResolvable` with `string` due to https://github.com/discordjs/discord.js/pull/4880
`StringResolvable` no longer exists, and the base discord.js lib will now enforce strings.
> fix: remove references to StringResolvable

- src/struct/ClientUtil.js
Client#fetchUser and Guild#fetchMember were removed in v11 and replaced with UserManager#fetch and GuildMemberManager#fetch respectfully (https://discordjs.guide/additional-info/changes-in-v12.html#fetch)
> Fixed outdated function references in ClientUtil

- src/struct/commands/CommandHandler.js
Correct docs as the event will be emitted even if a command has been found but blocked, for example by setting `channel: 'guild'` in the CommandOptions.
https://github.com/discord-akairo/discord-akairo/blob/29810b9e5d5cd804c649948ad60e5f2ac3897141/src/struct/commands/CommandHandler.js#L382
**I would highly recommend restructuring the logic to provide the behaivour that is currently advertised in the doc  instead of merging this**
> Update docs for CommandHandler messageInvalid event

- docs/other/mongoose.md
Changing `require` to `required` as it's not a supported property of `SchemaType`
> Fix of typo in mongoose provider guide

- src/index.d.ts
`AkairoClient`'s constructor accepts two overloads:
https://github.com/discord-akairo/discord-akairo/blob/3f00525d195f234331e5ddf15c742970d533fa3e/src/struct/AkairoClient.js#L12-L13
Which are:
- `AkairoOptions` as first argument, and d.js's `ClientOptions` as second.
- `AkairoOptions` and `ClientOptions` merged, when a second option is not passed.
The latter is achieved as `clientOptions` becomes `akairoOptions` when it's undefined.
| ℹ️ As a side note, those options will need to be revisited again when v13 releases, namely, removing `?:` from the first overload. |
| :---: |
> fix(types): overload `AkairoClient` constructor

- docs/snippets/ping.md
- src/index.d.ts
- src/struct/commands/CommandUtil.js
This fixes `CommandUtil` methods that send or edit a message to work with the upcoming Discord.js v13 release. It:
- Modifies `CommandUtil#reply` to use the new inline reply feature
- Modifies send/edit methods to take in only one `options` parameter which can be a string or a MessageOptions object
- Removes references to the removed `APIMessage#transformOptions`
> fix(CommandUtil): update send/edit methods for Discord.js v13

- src/struct/commands/arguments/Argument.js
Yet another v13 fix, this time for discordjs/discord.js#5903
> fix: move awaitMessages filter to options

- src/struct/AkairoClient.js
- src/struct/commands/CommandHandler.js
**This pull request fix the new `Id` syntax of [this commit](https://github.com/discordjs/discord.js/commit/a7c6678c7246025c4b358a5396dbacf4a73148ee)**
> fix: Usage of the `Id` syntax instead of the `ID` one

- src/struct/commands/CommandHandler.js
Per discordjs/discord.js#6114.
Also removes the usage of `.stopTyping()`, as that method was removed entirely.
> fix: Update startTyping -> sendTyping

- src/struct/commands/CommandHandler.js
Fixes the issue reported in the support server: [message](https://discord.com/channels/305153029567676426/387777801412935691/869948841733025852)
> discord.js removed `stopTyping` in v13/master-branch
> Remove stopTyping

- README.md
- src/struct/ClientUtil.js
- src/struct/commands/CommandHandler.js
- src/struct/commands/arguments/TypeResolver.js
Readme: Changed the required nodejs and discord.js versions. 
ClientUtil: Fixed the `compareStreaming` function to work properly.
CommandHandler: Fixed `parseCommand` would call `intoCallable` twice
TypeResolver: Changed `GUILD_MESSAGE` and `RELEVANT_MESSAGE` to `isText`(supports text, threads and news channels) instead of `GUILD_TEXT`
> cc: @1Computer1 - since discord.js v13 is stable now, should discord-akairo be updated on npm aswell, if so I can go ahead and change the version number (9.0.0)
> Bug fixes and updates
